#!/bin/sh
# combine annodc.owl and annods.owl and convert to anno.ttl.
SCRIPT_PATH=`dirname "$0"`
ROOT=`( cd "$SCRIPT_PATH/.." && pwd )`
DIST=$ROOT/dist

$SCRIPT_PATH/combine
pyshacl -s $ROOT/shacl.ttl -a -f human $DIST/anno.ttl | tee /tmp/shacl.txt
exit
