name: Combine ANNOdc and ANNOds, Deploy as RDF/Turtle

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get install -y raptor2-utils

      - name: Combine ANNOdc and ANNOds and serialize as RDF Turtle files
        # combine and print markdown tables with stats, show in GitHub
        run: scripts/combine | tee $GITHUB_STEP_SUMMARY

      - name: OLS 2 language support workaround
        run: scripts/olsworkaround

      - name: Deploy to the "dist" branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: dist
          folder: dist
          single-commit: true
